### PR TITLE
Close PtyProcess object instead of closing fd directly

### PR DESCRIPTION
**Pull request by takluyver**
@ellisonbg, I haven't got round to trying to reproduce the issue on your server, but I think I may have found one possible cause. If you have time, can you try installing from this branch and see if you can still reproduce the issue?

### CODE REVIEW

**Comment by ellisonbg** [comment]
Sure! Thanks for looking at this.

On Wed, Dec 9, 2015 at 9:35 AM, Thomas Kluyver <notifications@github.com>
wrote:

> @ellisonbg <https://github.com/ellisonbg>, I haven't got round to trying
> to reproduce the issue on your server, but I think I may have found one
> possible cause. If you have time, can you try installing from this branch
> and see if you can still reproduce the issue?
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/takluyver/terminado/pull/24
> Commit Summary
>
>    - Close PtyProcess object instead of closing fd directly
>
> File Changes
>
>    - *M* terminado/management.py
>    <https://github.com/takluyver/terminado/pull/24/files#diff-0> (7)
>
> Patch Links:
>
>    - https://github.com/takluyver/terminado/pull/24.patch
>    - https://github.com/takluyver/terminado/pull/24.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/takluyver/terminado/pull/24>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by ellisonbg** [comment]
Initial tests of this branch resolve the problem I am seeing. Two options:

* We merge this now and I continue to test and monitor the situations in master.
* I run this branch for a while to further confirm the fix.

I am fine with either. Thanks!

**Comment by takluyver** [comment]
Thanks. I'm going to merge it, as with your testing, I'm fairly sure that it's an improvement. There's another change I wanted to make - dropping support for Tornado < 4 - and then I'll aim to do a new release.

**Comment by ellisonbg** [comment]
Great, thanks!

On Thu, Dec 10, 2015 at 2:05 PM, Thomas Kluyver <notifications@github.com>
wrote:

> Merged #24 <https://github.com/takluyver/terminado/pull/24>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/takluyver/terminado/pull/24#event-488731787>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Pull request merged**
